### ISSUE TITLE
Add Installation + Usage Instructions to README

### ISSUE THREAD

**Issue by paige404** [tcyrus/homebrewery-standalone#1]
It's cool that this comes with a test markdown file, but the README includes no instructions for running it.

I'm not a JS developer, so running JS as an executable is very much a mystery to me.

**Comment by rjbprime** [comment]
@paige404: it seems you need the requirements for this as you would for the original homebrewery setup.

When you have these, you then go into the main directory of standalone, and in a command windows, run ``node install``, allowing standalone's requirements to install. You then follow that up with ``node bin/homebrewery.js test.md test.pdf`` to output the test file, to make sure everything is working.

It should then cause the command window to think for a few seconds, while it compiles the pdf. If you want to compile your own documents, replace the ``test.md``  in ``node bin/homebrewery.js test.md test.pdf`` with the name of the markdown file (``my-markdown.md``) you wrote, and ``test.pdf`` with the name of your output PDF (``my-pdf.pdf``). File names cannot have spaces, from what I can understand, as I *think* it will throw an error that will cause it to fail.

See if this helps. @tcyrus, is this accurate to how homebrewery-standalone was to be used?

**Comment by tcyrus** [comment]
@rjbprime: You should run `npm install` to download the requirements, instead of `node install`.

I removed a large chunk of the original Homebrewery app in order to reduce dependence as well as to make this easier to set up and use. This means that using the original setup instructions might overcomplicate things (for example, this doesn't require MongoDB).

@paige404: I'm sorry for not including proper setup instructions. I'll keep this issue open until I add proper instructions to the README.

**Comment by tcyrus** [comment]
Added "Quick Start" to README. I might need to work on this a bit more, but I'm marking this as closed as of now.
